openapi: 3.0.3
info:
  title: Bedrock Agent Alert Information API
  description: Retrieves detailed information about a specific alert by alert number.
  version: 1.0.0

paths:
  "/number":
    get:
      summary: Get alert details
      description: Retrieve detailed information about an alert using its alert number.
      operationId: getAlertInfo
      parameters:
        - name: number
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the alert
      responses:
        '200':
          description: Successful alert information retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  number:
                    type: string
                    example: "7"
                  created_at:
                    type: string
                    example: "2025-01-17 01:37:28+00:00"
                  dependency:
                    type: string
                    example: "{'package': {'ecosystem': 'npm', 'name': 'nanoid'}, 'manifest_path': 'package-lock.json', 'scope': 'development', 'relationship': 'unknown'}"
                  state:
                    type: string
                    example: "open"
                  repo:
                    type: string
                    example: "puppetOps"
                  security_advisory:
                    type: string
                    example: "{'ghsa_id': 'GHSA-mwcw-c2x4-8c55', 'cve_id': 'CVE-2024-55565', 'summary': 'Predictable results in nanoid generation when given non-integer values', 'description': 'When nanoid is called with a fractional value, there were a number of undesirable effects:\n\n1. in browser and non-secure, the code infinite loops on while (size--)\n2. in node, the value of poolOffset becomes fractional, causing calls to nanoid to return zeroes until the pool is next filled\n3. if the first call in node is a fractional argument, the initial buffer allocation fails with an error\n\nVersion 3.3.8 and 5.0.9 are fixed.', 'severity': 'medium', 'identifiers': [{'value': 'GHSA-mwcw-c2x4-8c55', 'type': 'GHSA'}, {'value': 'CVE-2024-55565', 'type': 'CVE'}], 'references': [{'url': 'https://nvd.nist.gov/vuln/detail/CVE-2024-55565'}, {'url': 'https://github.com/ai/nanoid/pull/510'}, {'url': 'https://github.com/ai/nanoid/compare/3.3.7...3.3.8'}, {'url': 'https://github.com/ai/nanoid/releases/tag/5.0.9'}, {'url': 'https://github.com/advisories/GHSA-mwcw-c2x4-8c55'}], 'published_at': '2024-12-09T03:30:59Z', 'updated_at': '2024-12-13T22:57:32Z', 'withdrawn_at': None, 'vulnerabilities': [{'package': {'ecosystem': 'npm', 'name': 'nanoid'}, 'severity': 'medium', 'vulnerable_version_range': '>= 4.0.0, < 5.0.9', 'first_patched_version': {'identifier': '5.0.9'}}, {'package': {'ecosystem': 'npm', 'name': 'nanoid'}, 'severity': 'medium', 'vulnerable_version_range': '< 3.3.8', 'first_patched_version': {'identifier': '3.3.8'}}], 'cvss_severities': {'cvss_v3': {'vector_string': 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N', 'score': 4.3}, 'cvss_v4': {'vector_string': None, 'score': 0.0}}, 'epss': {'percentage': 0.00030000000000000003, 'percentile': 0.06975}, 'cvss': {'vector_string': 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N', 'score': 4.3}, 'cwes': [{'cwe_id': 'CWE-835', 'name': "Loop with Unreachable Exit Condition ('Infinite Loop')"}]}"
                  security_vulnerability:
                    type: string
                    example: "{'package': {'ecosystem': 'npm', 'name': 'nanoid'}, 'severity': 'medium', 'vulnerable_version_range': '< 3.3.8', 'first_patched_version': {'identifier': '3.3.8'}}"
                  url:
                    type: string
                    example: "https://api.github.com/repos/mgbec/amplify-vite-react-template/dependabot/alerts/1"


        '404':
          description: Alert not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alert not found"
        '500':
          description: Internal server error

components:
  schemas:
    Alert:
      type: object
      properties:
        number:
          type: string
        created_at:
          type: string
        dependency:
          type: string
        state:
          type: string
        repo:
          type: string
        security_advisory:
          type: string
        security_vulnerability
          type: string
        url:
          type: string
