openapi: 3.0.3
info:
  title: Bedrock Agent Alert Information API
  description: Retrieves detailed information about a specific alert by alert number.
  version: 1.0.0

paths:
  "/alert_id":
    get:
      summary: Get alert details
      description: Retrieve detailed information about an alert using its alert number.
      operationId: getAlertStatus
      parameters:
        - name: alert_id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the alert
      responses:
        '200':
          description: Successful alert information retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  alert_id:
                    type: integer
                    example: "ALRT-123456"
                  alert_title:
                    type: string
                    example: "Pillow vuln xyz123"
                  severity:
                    type: string
                    enum: [Low, Medium, High, Critical]
                    example: "Critical"
                  alert_status:
                    type: string
                    enum: [Open, In Progress, Resolved, Closed]
                    example: "Open"
                  repo:
                    type: string
                    example: "Infrastructure Ops"
        '404':
          description: Alert not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alert not found"
        '500':
          description: Internal server error

components:
  schemas:
    Alert:
      type: object
      properties:
        alert_id:
          type: integer
        alert_title:
          type: string
        severity:
          type: string
        status:
          type: string
        repo:
          type: string
